### ISSUE TITLE
what‘’s the “（raw）and （filter）”in the final experimental result

### ISSUE THREAD

**Issue by MEwlj** [hopkin-ghp/QuatDE#1]
您好，初步了解了一下openKE的框架，但还是不了解结果中的括号内的（raw）和（filter）是什么意思

**Comment by MEwlj** [comment]
能留给兄弟您的联系 方式吗

**Comment by hopkin-ghp** [comment]
raw和filter的区别：（1）训练集里只包含正样本，在随机构造负样本的时候，需要过滤掉假负样本（出现在训练集里的样本）；（2），做预测的时候，比如计算排名MR，也需要过滤掉训练集的样本。

**Comment by MEwlj** [comment]
> raw和filter的区别：（1）训练集里只包含正样本，在随机构造负样本的时候，需要过滤掉假负样本（出现在训练集里的样本）；（2），做预测的时候，比如计算排名MR，也需要过滤掉训练集的样本。

好的，训练结果中的type constraint是什么呢，而且只有type constraint results中有classification分类结果

**Comment by hopkin-ghp** [comment]
> > raw和filter的区别：（1）训练集里只包含正样本，在随机构造负样本的时候，需要过滤掉假负样本（出现在训练集里的样本）；（2），做预测的时候，比如计算排名MR，也需要过滤掉训练集的样本。
> 
> 好的，训练结果中的type constraint是什么呢，而且只有type constraint results中有classification分类结果

建议你先去看看openKE的readme文件哈，那里都有写的
