### ISSUE TITLE
Hi, for QuatE, did your experimental results run as written in the paper ?

### ISSUE THREAD

**Issue by stevenlyf428** [hopkin-ghp/QuatDE#2]
![image](https://user-images.githubusercontent.com/42695164/167287491-d495edd8-6d86-4093-b192-4d3f09b9d6d7.png)
![image](https://user-images.githubusercontent.com/42695164/167287521-69927c6d-0675-4503-894a-21e70c4e644a.png)

take FB5K-237 dataset as an example

**Comment by hopkin-ghp** [comment]
Thanks for your attention, the experimental results of QuatE im my paper are taken from the original paper, and i run the code as QuatE

**Comment by stevenlyf428** [comment]
I run the QuatE  and the result is "Hit@1 **0.256** Hit@3 **0.381** Hit@10 **0.536**".(the right picture)
But the paper writes "24.8 38.2 55.0".
For the Hit@10, the result is nearly 1.4 percent difference.
So I want to ask if you have this question?

Sorry to ask you this question. Because the QuatE [code](https://github.com/cheungdaven/QuatE) have not Issue button.

**Comment by hopkin-ghp** [comment]
Sorry，I forgot the exact result of QuatE I reproduced, but it seems to be a little different from the original.

**Comment by stevenlyf428** [comment]
Thanks!!!!!!!
